// Build script: N2 vocab game data from OpenJLPT data files.
// Usage: node build.js
// Reads: <temp>/jlpt_n2_vocab.json + kanji_all.json   (or local copies)
// Writes: n2data.js  (embedded dataset used by index.html)

const fs = require('fs');
const path = require('path');

const TMP = 'C:/Users/wacio/AppData/Local/Temp/opencode';
const READ = {
  vocab: path.join(TMP, 'jlpt_n2_vocab.json'),
  kanji: path.join(TMP, 'kanji_all.json'),
  krad: path.join(TMP, 'krad_utf8.txt'),
};

// kradfile2 format (UTF-8): `<kanji> : <radical> <radical> ...`
function readKrad() {
  const map = {};
  const lines = fs.readFileSync(READ.krad, 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const m = /^(\S+)\s*:\s*(.*)$/.exec(line.trim());
    if (!m) continue;
    const rads = (m[2] || '').split(/\s+/).filter(Boolean);
    if (rads.length) map[m[1]] = rads;
  }
  return map;
}

const VERB_END = /(る|く|ぐ|す|つ|ぬ|ぶ|む)([うっってだたなは]?)$/; // only used as hint

function classify(word, mean) {
  const m0 = (mean && mean[0]) || '';
  if (/^to\s/i.test(m0)) {
    return 'V';
  }
  // い-adjective: kanji + い ending (or known kana words)
  if (/[一-龯].*(い|しい|ない)$/.test(word) && !/(合い|違い|勝ち|負け)味?$/.test(word) && !/(賞味|物知り)$/.test(word)) return 'I';
  if (KANA_IA.indexOf(word) >= 0) return 'I';
  return 'N';
}

const KANA_IA = [
  'あいまい', 'あわただしい', 'きびしい', 'くわしい', 'したしい', 'すばらしい',
  'なつかしい', 'めんどうくさい', 'もったいない', 'やかましい', 'やわらかい',
  'おとなしい', 'おめでたい', 'ひどい', 'まずい', 'まぎらわしい', 'はなはだしい',
  'しつこい', 'まぶしい', 'とぼしい', 'ひとしい', 'しぶい', 'あつかましい',
  'こまかい', 'なだかい', 'すこやか（な）', 'やわらか（な）',
];

const THEME_KEYWORDS = {
  travel: ['travel', 'trip', 'journey', 'excursion', 'tour', 'station', 'ticket', 'luggage', 'hotel', 'voyage', 'visit', 'passport', 'airport', 'sightseeing'],
  work: ['work', 'company', 'office', 'business', 'employee', 'job', 'salary', 'meeting', 'conference', 'employment', 'interview', 'colleague', 'factory', 'labor', 'management'],
  food: ['food', 'eat', 'drink', 'cook', 'meal', 'taste', 'dish', 'restaurant', 'market', 'cuisine', 'hunger', 'thirst', 'sweet', 'bitter', 'salty', 'rye'],
  nature: ['mountain', 'sea', 'river', 'forest', 'weather', 'rain', 'sky', 'wind', 'mile', 'wave', 'snow', 'cloud', 'sun', 'earth', 'nature', 'flower', 'tree', 'plant', 'field', 'island'],
  city: ['city', 'town', 'street', 'building', 'district', 'ward', 'train', 'road', 'bridge', 'tunnel', 'traffic', 'crowd', 'stadium'],
  home: ['house', 'home', 'room', 'furniture', 'kitchen', 'bath', 'closet', 'repair', 'rent', 'move', 'moving', 'neighbor'],
  emotion: ['feel', 'feeling', 'emotion', 'sad', 'happy', 'angry', 'heart', 'mind', 'worry', 'fear', 'joy', 'grief', 'disappoint', 'anxiety', 'comfort', 'pleasur', 'hope', 'fear', 'timid'],
  health: ['hospital', 'doctor', 'medicine', 'health', 'body', 'pain', 'sick', 'disease', 'blood', 'fever', 'cough', 'hurt', 'wound', 'cure', 'patient', 'surgery', 'illness'],
  money: ['money', 'price', 'pay', 'sell', 'buy', 'tax', 'sale', 'trade', 'economy', 'account', 'budget', 'debt', 'wealth', 'cost', 'profit', 'loss', 'discount', 'currency'],
  time: ['time', 'day', 'year', 'hour', 'today', 'tomorrow', 'yesterday', 'period', 'age', 'moment', 'dawn', 'sometimes', 'regularly', 'schedule', 'appointment', 'always', 'temporarily'],
  study: ['study', 'learn', 'school', 'exam', 'test', 'student', 'lesson', 'knowledge', 'research', 'education', 'university', 'memorize', 'practice', 'lecture', 'word', 'kanji', 'writing'],
  society: ['society', 'politics', 'government', 'law', 'crime', 'war', 'peace', 'party', 'nation', 'public', 'court', 'responsib', 'duty', 'custom', 'culture', 'religion', 'tradition'],
};

function themeForMeanings(meanings) {
  const hay = (meanings || []).join(' ').toLowerCase();
  let best = null, bestN = 0;
  for (const t in THEME_KEYWORDS) {
    let n = 0;
    for (const kw of THEME_KEYWORDS[t]) if (hay.includes(kw)) n++;
    if (n > bestN) { best = t; bestN = n; }
  }
  return best || 'general';
}

// ---- Polish translations (curated). Key = dictionary form from dataset. ----
const PL = {
  'あいかわらず': 'jak zwykle, niezmiennie',
  'アイデア': 'pomysł, idea',
  'あいまい': 'niejasny, dwuznaczny, mglisty',
  'あかんぼう': 'niemowlę',
  'あきれる': 'być zdumionym, osłupiałym',
  'アクセント': 'akcent, nacisk',
  'あくび': 'ziewanie',
  'あたりまえ': 'oczywistość; oczywiste',
  'あちらこちら': 'tu i tam, tam i z powrotem; wszędzie',
  'あてはまる': 'pasować, mieć zastosowanie',
  'あてはめる': 'dopasowywać, stosować (regułę)',
  'あぶる': 'piec nad ogniem, opiekać',
  'あふれる': 'przelewać się, być przepełnionym',
  'あらすじ': 'streszczenie, zarys fabuły',
  'あれこれ': 'to i owo; różne rzeczy',
  'あわただしい': 'gorączkowy, zabiegany, chaotyczny',
  'あわてる': 'panikować, gorączkować się',
  'アンテナ': 'antena',
  'いきなり': 'nagle, znienacka',
  'イコール': 'równa się; znak równości',
  'いちいち': 'za każdym razem; punkt po punkcie',
  'いつのまにか': 'niepostrzeżenie, nie wiedzieć kiedy',
  'いよいよ': 'wreszcie, coraz bardziej; naprawdę',
  'インタビュー': 'wywiad',
  'ウーマン': 'kobieta',
  'ウール': 'wełna',
  'ウエートレス': 'kelnerka',
  'うっかり': 'nieuważnie, przez nieuwagę',
  'うどん': 'udon (gruby makaron pszenny)',
  'うろうろ': 'błąkać się, kręcić się bez celu',
  'うんと': 'bardzo dużo, mnóstwo; dzielnie',
  'ええと': 'yyy…, no więc (słowo wahania)',
  'エチケット': 'etykieta, dobre maniery',
  'エプロン': 'fartuch, zapaska',
  'オイル': 'olej',
  'オーケストラ': 'orkiestra',
  'おおざっぱ': 'zgrubny, pobieżny, niedokładny',
  'オートメーション': 'automatyzacja',
  'おかげさまで': 'dzięki Bogu, dzięki panu (grzecznościowo)',
  'おかず': 'danie dodatkowe (podawane do ryżu)',
  'おくさん': 'żona (czyjaś, grzecznie)',
  'おさきに': 'najpierw; trafny zwrot przy wyjściu: „przepraszam, odchodzę"',
  'おじゃまします': 'przepraszam, że przeszkadzam',
  'おしゃれ': 'elegancja; elegancki, wystrojony',
  'おだいじに': '„dbaj o siebie" (do chorego)',
  'おどかす': 'straszyć, przerażać',
  'おととい': 'przedwczoraj',
  'おととし': 'przeszły rok (dwa lata temu)',
  'おとなしい': 'grzeczny, spokojny, cichy',
  'おねがいします': 'proszę (o pomoc/przysługę)',
  'おまたせしました': 'przepraszam, że kazałem/am czekać',
  'おまちください': 'proszę (chwilę) poczekać',
  'おまちどおさま': 'dzięki za cierpliwość (przeprosiny za czekanie)',
  'おめでたい': 'radosny, szczęśliwy (o wydarzeniu)',
  'おやつ': 'przekąska, drugie śniadanie',
  'オルガン': 'organy (instrument)',
  'あんまり': 'niezbyt, bardzo (potocznie)',
  'いずれ': 'kiedyś, prędzej czy później',
  'いずれにせよ': 'w każdym razie',
  'いただきます': '„smacznego" (przed jedzeniem)',
  'ありがとうございました': 'dziękuję bardzo (za to, co było)',
  'あんぜん': 'bezpieczeństwo; bezpiecznie',
  '明け方': 'świt, świt dnia',
  '青白い': 'bladawy, blady',
  '足跡': 'ślady stóp',
  '売買': 'kupno i sprzedaż, handel',
  '売店': 'budka/kiosk sprzedażowy',
  '募集': 'nabór, rekrutacja',
  '長男': 'najstarszy syn',
  '楕円': 'elipsa',
  '大学院': 'szkoła podyplomowa, studia magisterskie/doktoranckie',
  '出入口': 'wejście i wyjście',
  '宴会': 'bankiet, przyjęcie',
  '円周': 'obwód koła',
  '遠足': 'wycieczka (szkolna)',
  '父母': 'rodzice, ojciec i matka',
  '学科': 'kierunek studiów, przedmiot',
  '学会': 'konferencja naukowa, towarzystwo naukowe',
  '学力': 'zdolność/stosunek do nauki',
  '外科': 'chirurgia',
  '花火': 'fajerwerki',
  '半径': 'promień (mat.)',
  '半島': 'półwysep',
  '発売': 'sprzedaż, wprowadzenie do sprzedaży',
  '早口': 'szybkie mówienie',
  '外れる': 'wypaść, odpaść; być nietrafnym',
  '閉会': 'zamknięcie obrad',
  '昼寝': 'drzemka w południe',
  '意地悪': 'złośliwość; złośliwy',
  '移転': 'przeniesienie, przeprowadzka',
  '一旦': 'na razie, chwilowo',
  '寺院': 'świątynia buddyjska',
  '速達': 'przesyłka ekspresowa',
  '輸血': 'transfuzja krwi',
  '輸送': 'transport, przewóz',
  '自習': 'nauka samodzielna',
  '実習': 'praktyka, zajęcia praktyczne',
  '開会': 'otwarcie (posiedzenia itp.)',
  '回転': 'obrót, rotacja',
  '加速': 'przyspieszenie',
  '見学': 'zwiedzanie (zwiedzanie z nauką)',
  '転がる': 'toczyć się, przewrócić się',
  '転がす': 'toczyć, przewracać (coś)',
  '待ち合わせる': 'spotkać się w umówionym miejscu',
  '入社': 'wstąpienie do firmy (pracę)',
  '押さえる': 'przyciskać, przytrzymywać',
  '領収': 'pokwitowanie, otrzymanie płatności',
  '刺さる': 'wbić się, wpić się (kolce)',
  '刺す': 'kłuć, dźgać, żądlić',
  '司会': 'prowadzenie (programu, zebrania)',
  '集合': 'zbiórka, zebranie się',
  '集会': 'mityng, zebranie, zgromadzenie',
  '足る': 'wystarczać, być wystarczającym',
  '特売': 'wyprzedaż, specjalna promocja',
  '売り切れる': 'wyprzedać się',
  '改正': 'nowelizacja, poprawka (prawa)',
  '強化': 'wzmocnienie, umocnienie',
  '交流': 'wymiana, obcowanie, kontakty',
  '構造': 'struktura, konstrukcja',
  '姿勢': 'postawa, pozycja; podejście',
  '周辺': 'okolica, pobliże, peryferia',
  '政党': 'partia polityczna',
  '体制': 'system, ustrój, struktura',
  '対策': 'środki zaradcze, strategia',
  '段階': 'etap, stadium, poziom',
  '損得': 'zysk i strata',
  '利益': 'zysk, korzyść',
  '影響': 'wpływ, oddziaływanie',
  '経験': 'doświadczenie',
  '経済': 'gospodarka, ekonomia',
  '効果': 'efekt, skutek',
  '環境': 'środowisko, otoczenie',
  '関係': 'związek, relacja',
  '機械': 'maszyna',
  '機会': 'okazja, sposobność',
  '性格': 'charakter, usposobienie',
  '習慣': 'nawyk, zwyczaj',
  '実感': 'odczucie, realne odczucie',
  '自由': 'wolność, swoboda',
  '準備': 'przygotowanie',
  '情報': 'informacja',
  '商品': 'towar, produkt',
  '製造': 'produkcja, wytwarzanie',
  '説明': 'wyjaśnienie, objaśnienie',
  '世界': 'świat',
  '世話': 'opieka, troska',
  '生活': 'życie, tryb życia',
  '成長': 'rozwój, wzrost',
  '速度': 'prędkość, szybkość',
  '相談': 'konsultacja, narada',
  '存在': 'istnienie, byt',
  '対応': 'reakcja, radzenie sobie (z czymś)',
  '単語': 'słowo, wyraz',
  '知識': 'wiedza',
  '調査': 'badanie, dochodzenie',
  '特徴': 'cecha charakterystyczna',
  '程度': 'stopień, zakres',
  '追加': 'dodanie, uzupełnienie',
  '集中': 'koncentracja, skupienie',
  '重視': 'cenienie, przywiązywanie wagi',
  '責任': 'odpowiedzialność',
  '配る': 'rozdawać, rozdzielać',
  '比べる': 'porównywać',
  '基礎': 'podstawa, fundament',
  '応用': 'zastosowanie, zastosowanie praktyczne',
  '対象': 'obiekt, przedmiot (działania)',
  '意欲': 'chęć, motywacja, zapał',
  '価値': 'wartość',
  '価格': 'cena',
  '能力': 'umiejętność, zdolność',
  '十分': 'wystarczająco, dostatecznie',
  '豊か': 'bogaty, obfity',
  '貧しい': 'biedny, ubogi',
  '詳しい': 'szczegółowy; dobrze obeznany',
  '効率': 'wydajność, efektywność',
  '積極的': 'aktywny, pozytywny, proaktywny',
  '消極的': 'pasywny, bierny',
  '率直': 'szczery, otwarty',
  '真剣': 'poważny (w wysiłku), zaangażowany',
  '熱心': 'gorliwy, zapalony',
  '適当': 'odpowiedni, właściwy',
  '適切': 'trafny, właściwy',
  '明確': 'jasny, wyraźny, jednoznaczny',
  '簡潔': 'zwięzły, lakoniczny',
  '複雑': 'skomplikowany',
  '単純': 'prosty, prostolinijny',
  '巨大': 'ogromny, gigantyczny',
  '広大': 'rozległy, obszerny',
  '貴重': 'cenny, wartościowy',
  '重要': 'ważny, istotny',
  '重大': 'poważny, doniosły',
  '優しい': 'łagodny, miły, delikatny',
  '厳しい': 'surowy, srogi',
  '激しい': 'gwałtowny, intensywny',
  '珍しい': 'rzadki, niezwykły',
  '懐かしい': 'budzący nostalgię, tęskny',
  '柔らかい': 'miękki',
  '硬い': 'twardy, sztywny',
  '慌ただしい': 'gorączkowy, zabiegany, chaotyczny',
  '滑らか': 'gładki, płynny',
  '隅々': 'każdy zakątek',
  '隙間': 'szczelina, szpara',
  '枠': 'rama, obręb, zakres',
  '裏': 'tył, odwrotna strona; wnętrze',
  '表': 'tabela; przód, powierzchnia',
  '横': 'bok, szerokość',
  '縦': 'pion, długość (w pionie)',
  '順番': 'kolejność',
  '逆': 'odwrót, przeciwieństwo',
  '互いに': 'wzajemnie, nawzajem',
  '再び': 'znowu, ponownie',
  '急に': 'nagle',
  '徐々に': 'stopniowo, powoli',
  'だんだん': 'stopniowo',
  'ますます': 'coraz bardziej',
  '真実': 'prawda, rzeczywistość',
  '是非': 'koniecznie; pod żadnym pozorem przeciwnie',
  '絶対': 'absolutnie, z całą pewnością',
  '必ず': 'na pewno, zawsze',
  '必ずしも': 'niekoniecznie',
  '並ぶ': 'ustawiać się w szeregu, stać w kolejce',
  '並べる': 'ustawiać, układać (w szereg)',
  '積む': 'układać w stos, ładować',
  '積もる': 'gromadzić się, spiętrzać się',
  '広げる': 'rozkładać, rozszerzać',
  '広がる': 'rozprzestrzeniać się',
  '磨く': 'polerować, czyścić, szlifować',
  '洗う': 'myć',
  '入れる': 'wkładać do środka',
  '出かける': 'wychodzić (z domu)',
  '戻る': 'wracać',
  '帰る': 'wracać do domu',
  '届く': 'docierać, być dostarczonym',
  '届ける': 'dostarczać, zgłaszać',
  '探す': 'szukać',
  '探る': 'badać, wypytywać, sondująco szukać',
  '防ぐ': 'zapobiegać, bronić',
  '守る': 'chronić, przestrzegać',
  '助ける': 'pomagać, ratować',
  '助かる': 'być uratowanym, ratować się',
  '救う': 'ratować',
  '整える': 'doprowadzać do porządku, przygotować',
  '整う': 'być uporządkowanym, być gotowym',
  '揃える': 'skompletować, doprowadzić do równego stanu',
  '揃う': 'skompletować się, zebrać się',
  '満たす': 'wypełniać, zaspokajać',
  '満ちる': 'być pełnym, wypełniać się',
  '抱く': 'obejmować; żywić (uczucie)',
  '抱える': 'trzymać w ramionach; mieć (problem)',
  '支える': 'wspierać, podpierać',
  '支払う': 'płacić',
  '払う': 'płacić, uiścić',
  '払い込む': 'wpłacać, wnosić opłatę',
  '預ける': 'powierzać, składać w depozyt',
  '預かる': 'przyjąć na przechowanie',
  '借りる': 'pożyczać (od kogoś)',
  '貸す': 'pożyczać (komuś), wypożyczać',
  '返す': 'oddać, zwrócić',
  '返る': 'wracać, być zwróconym',
  '滑る': 'ślizgać się, poślizgnąć się',
  '転ぶ': 'przewrócić się, wywrócić się',
  '落ちる': 'spadać, opadać',
  '落とす': 'gubić, upuszczać',
  '落ち着く': 'uspokajać się, osiedlać się',
  '解決': 'rozwiązanie (problemu)',
  '判断': 'osąd, ocena, decyzja',
  '決心': 'postanowienie, decyzja',
  '決意': 'postanowienie, determinacja',
  '覚悟': 'gotowość (na złe), determinacja',
  '挑戦': 'wyzwanie, próba',
  '努力': 'wysiłek, staranie',
  '励む': 'starać się, być oddanym (pracy)',
  '怠る': 'zaniedbywać, być niedbałym',
  '怠け者': 'leń, leniwiec',
  '油断': 'nieuwaga, roztargnienie',
  '注意': 'uwaga, ostrożność',
  '警告': 'ostrzeżenie',
  '忠告': 'rada, ostrzeżenie',
  '提案': 'propozycja, wniosek',
  '意見': 'opinia, zdanie',
  '感想': 'wrażenia, refleksje',
  '印象': 'wrażenie',
  '予定': 'plan, harmonogram',
  '予定通り': 'zgodnie z planem',
  '予約': 'rezerwacja',
  '延期': 'odroczenie, przełożenie (terminu)',
  '延ばす': 'wydłużać, przedłużać',
  '延びる': 'wydłużać się, przedłużać się',
  '伸ばす': 'rozciągać, wyciągać; rozwijać',
  '伸びる': 'rozciągać się; rosnąć, rozwijać się',
  '縮める': 'skracać, kurczyć',
  '縮む': 'kurczyć się, skracać się',
  '減る': 'ubywać, zmniejszać się',
  '減らす': 'zmniejszać, redukować',
  '増える': 'wzrastać, zwiększać się',
  '増やす': 'zwiększać',
  '疲れる': 'męczyć się',
  '疲れ': 'zmęczenie',
  '疲労': 'zmęczenie, znużenie',
  '眠気': 'senność',
  '目覚める': 'obudzić się, ocknąć się',
  '目覚まし': 'budzik',
  '眠る': 'spać, drzemać',
  '寝返る': 'przewracać się w łóżku',
  '暮らす': 'żyć, prowadzić (życie)',
  '暮れる': 'zapadać (zapada wieczór); kończyć się (rok)',
  '明るい': 'jasny, pogodny',
  '暗い': 'ciemny, ponury',
  '曇る': 'chmurzyć się, robić się pochmurno',
  '晴れる': 'rozpogadzać się',
  '晴らす': 'rozjaśniać, rozwiewać (smutek)',
  '降る': 'padać (deszcz, śnieg)',
  '吹く': 'wiać, dmuchać',
  '照る': 'świecić (słońce)',
  '光る': 'świecić, błyszczeć',
  '光': 'światło, blask',
  '影': 'cień',
  '景色': 'krajobraz, widok',
  '風景': 'krajobraz, pejzaż',
  '眺め': 'widok, panorama',
  '眺める': 'przyglądać się (dalekom widokowi)',
  '眺望': 'widok, panorama',
  '抜ける': 'wypadać, wyrywać się; przechodzić przez',
  '抜く': 'wyrywać, usuwać',
  '浮かぶ': 'unosić się; przyjść na myśl',
  '浮かべる': 'unosić na wodzie; rysować (uśmiech)',
  '沈む': 'tonąć, opadać na dno',
  '沈める': 'topić, zatapiać',
  '湧く': 'tryskać, wytryskiwać; rodzić się (uczucie)',
  '沸く': 'gotować się, wrzeć',
  '沸かす': 'gotować (coś), doprowadzać do wrzenia',
  '凍る': 'zamarzać, lodowacieć',
  '凍える': 'marznąć, kostnieć',
  '溶ける': 'topić się, rozpuszczać się',
  '溶かす': 'topić, rozpuszczać',
  '焼く': 'piec, palić, opalać',
  '焼ける': 'piec się, spalać się',
  '焦げる': 'przypalać się',
  '焦る': 'być zniecierpliwionym, gorączkować się',
  '暑い': 'gorąco (o pogodzie)',
  '寒い': 'zimno (o pogodzie)',
  '涼しい': 'chłodny, rześki',
  '暖かい': 'ciepły',
  '冷える': 'oziębiać się, stygnąć',
  '冷める': 'stygnąć, wystygać',
  '冷ます': 'studzić, oziębiać',
  '涼む': 'chłodzić się, ochładzać się',
  '乾く': 'wysychać, schnąć',
  '乾かす': 'suszyć',
  '濡れる': 'zmoknąć, zamoknąć',
  '濡らす': 'moczyć, zwilżać',
  '湿る': 'nabierać wilgoci, wilgotnieć',
  '腐る': 'psuć się, gnić',
  '腐らす': 'doprowadzać do zepsucia',
  '錆びる': 'rdzewieć',
  '錆': 'rdza',
  '壊れる': 'psuć się, rozbijać się',
  '壊す': 'psuć, rozbijać',
  '直る': 'naprawiać się, poprawiać się',
  '直す': 'naprawiać, poprawiać',
  '治る': 'wracać do zdrowia, leczyć się (wyleczyć się)',
  '治す': 'leczyć',
  '効く': 'działać, być skutecznym',
  '効き目': 'skuteczność, działanie (leku)',
  '及ぶ': 'sięgać, sięgać (do czegoś)',
  '及ぼす': 'wywierać (wpływ)',
  '及ぶほど': '—',
  '関わる': 'być związanym, dotyczyć',
  '関する': 'dotyczyć, dotykać',
  '含む': 'zawierać, obejmować',
  '含める': 'obejmować, wliczać',
  '伴う': 'towarzyszyć, pociągać za sobą',
  '従う': 'podążać, być posłusznym',
  '従える': 'mieć pod sobą; poskramiać',
  '寄る': 'zbliżać się; wstępować (po drodze)',
  '寄せる': 'przybliżać; składać (daninę)',
  '近づく': 'zbliżać się',
  '近づける': 'przybliżać, dopuszczać bliżej',
  '遠ざかる': 'oddalać się',
  '遠ざける': 'trzymać z daleka, oddalać',
  '離れる': 'oddalać się, rozstawać się',
  '離す': 'odsuwać, wypuszczać',
  'はずれる': 'wypaść (np. z zawiasów); być nietrafnym',
  'ことわる': 'odmawiać, odrzucać',
  'うつむく': 'pochylać głowę, wpatrywać się w ziemię',
  'うつす': 'przepisywać, kopiować; odbijać',
  'うつる': 'odbijać się, przechodzić (elektryzacja, choroba)',
  'こらす': 'wytężać, koncentrować (wzrok, uwagę)',
  'ためる': 'gromadzić, oszczędzać',
  'たまる': 'gromadzić się',
  'くぐる': 'przechodzić pod czymś; przekraczać',
  'つまずく': 'potknąć się, zawieść',
  'つまずき': 'potknięcie, przeszkoda',
  'つぶす': 'miażdżyć, zgniatać; zabijać (czas)',
  'つぶれる': 'zgniatać się, rozpadać się',
  'つぶやく': 'mamrotać, mruczeć',
  'つなぐ': 'łączyć, wiązać',
  'つながる': 'łączyć się, być połączonym',
  'つける': 'przyczepiać, zapalać, prowadzić (dziennik)',
  'つかう': 'używać, zużywać',
  'まねく': 'zapraszać, wzywać',
  'まねる': 'naśladować',
  'ならう': 'uczyć się (od kogoś)',
  'ならぶ': 'stać w szeregu',
  'ならべる': 'stawiać w szeregu',
  'はじまる': 'zaczynać się',
  'はじめる': 'zaczynać',
  'おわる': 'kończyć się',
  'おえる': 'kończyć, kończyć (pracę)',
  'すすむ': 'posuwać się naprzód, postępować',
  'すすめる': 'posuwać naprzód; rekomendować',
  'とまる': 'zatrzymywać się, przestać',
  'とめる': 'zatrzymywać, przerywać',
  'やむ': 'ustawać, przestawać (deszcz)',
  'やめる': 'przestawać, rezygnować',
  'かいけつ': 'rozwiązanie (problemu)',
  'げんいん': 'przyczyna',
  'げんか': 'robić coś intensywnie... —',
  'まずしい': 'biedny, ubogi',
  'ただしい': 'poprawny, właściwy',
  'すくない': 'mało, niewiele',
  'おおい': 'dużo, wiele',
  'あつい': 'gorący, upalny',
  'つめたい': 'zimny',
  'あたたかい': 'ciepły',
  'そら': 'niebo',
  'うみ': 'morze',
  'やま': 'góra',
  'かわ': 'rzeka',
  'みち': 'droga',
  'まち': 'miasto, miejscowość',
  'むら': 'wieś',
  'はし': 'most',
  'ビル': 'wieżowiec, budynek',
  'ホテル': 'hotel',
  '駅': 'stacja',
  '空港': 'port lotniczy',
  '港': 'port',
  '公園': 'park',
  '庭': 'ogród, podwórko',
  '畑': 'pole uprawne, warzywnik',
  '田んぼ': 'pole ryżowe',
  '農業': 'rolnictwo',
  '工場': 'fabryka',
  '事務所': 'biuro',
  '警察': 'policja',
  '税務署': 'urząd skarbowy',
  '裁判所': 'sąd, trybunał',
  '会議室': 'sala konferencyjna',
  '受付': 'recepcja, punkt informacyjny',
  '窓口': 'okienko, punkt obsługi',
  '階段': 'schody',
  '玄関': 'wejście, przedsionek',
  '廊下': 'korytarz',
  '屋根': 'dach',
  '壁': 'ściana',
  '柱': 'filar, kolumna',
  '敷地': 'działka, teren',
  '倉庫': 'magazyn',
  '貯金': 'oszczędności',
  '貯める': 'oszczędzać, odkładać',
  '金持ち': 'bogacz; bogaty',
  '掛け値': 'zawyżanie ceny',
  '値段': 'cena',
  '値上げ': 'podwyżka ceny',
  '値下げ': 'obniżka ceny',
  '収入': 'dochód',
  '支出': 'wydatek',
  '節約': 'oszczędzanie',
  '浪費': 'marnotrawstwo',
  '給料': 'pensja, wynagrodzenie',
  '賃金': 'płaca, wynagrodzenie',
  '家賃': 'czynsz',
  '月給': 'miesięczna pensja',
  '交渉': 'negocjacje',
  '契約': 'umowa, kontrakt',
  '注文': 'zamówienie',
  '注文する': 'zamawiać',
  '代金': 'należność, cena (za towar)',
  '返金': 'zwrot pieniędzy',
  '両替': 'wymiana waluty',
  '為替': 'kurs wymiany; przekaz pieniężny',
  'インターネット': 'internet',
  'コンピューター': 'komputer',
  '番組': 'program (telewizyjny)',
  '録音': 'nagranie (dźwięku)',
  '放送': 'nadawanie, transmisja, audycja',
  '報道': 'relacje, doniesienia (prasowe)',
  '記事': 'artykuł (prasowy)',
  '紙面': 'łam prasowy, strona gazety',
  '情報源': 'źródło informacji',
  '連絡': 'kontakt, zawiadomienie',
  '通信': 'komunikacja, łączność',
  '郵便': 'poczta',
  '小包': 'paczka (pocztowa)',
  '封筒': 'koperta',
  '切手': 'znaczek pocztowy',
  'はがき': 'pocztówka, karta pocztowa',
  '受信': 'odbiór (sygnału)',
  '送信': 'nadanie (sygnału), przesłanie',
  '出張': 'podróż służbowa',
  '人事': 'sprawy kadrowe, HR',
  '就職': 'znalezienie pracy',
  '失業': 'bezrobocie',
  '職場': 'miejsce pracy',
  '部署': 'dział, sekcja',
  '上司': 'przełożony',
  '部下': 'podwładny',
  '同僚': 'współpracownik',
  '定年': 'wiek emerytalny',
  '退職': 'odejście z pracy, przejście na emeryturę',
  '期間': 'okres, czas trwania',
  '期限': 'termin, ostateczny czas',
  '延長': 'przedłużenie',
  '省略': 'pominięcie, skrót',
  '詳細': 'szczegóły, detale',
  '手順': 'kolejność postępowania, procedura',
  '手段': 'środek, sposób, metoda',
  '方法': 'metoda, sposób',
  '目的': 'cel',
  '目標': 'cel, miernik',
  '結果': 'wynik, rezultat',
  '原因': 'przyczyna',
  '理由': 'powód, przyczyna',
  '根拠': 'podstawa, uzasadnienie',
  '証拠': 'dowód, świadek',
  '確信': 'przekonanie, pewność',
  '自信': 'pewność siebie',
  '勇気': 'odwaga',
  '忍耐': 'cierpliwość, wytrwałość',
  '我慢': 'wytrwałość, tolerowanie, は entra... powściągliwość',
  '苦労': 'trud, kłopoty, zmagania',
  '緊張': 'napięcie, zdenerwowanie',
  '慌てる': 'spanikować, gorączkować się',
  '恐怖': 'strach, przerażenie',
  '感動': 'wzruszenie',
  '充実': 'pełnia, bycie spełnionym',
  '達成': 'osiągnięcie (celu)',
  '夢中': 'bycie w euforii, wciągnięcie się',
  '興味': 'zainteresowanie',
  '関心': 'zainteresowanie, troska',
  '好奇心': 'ciekawość',
  '納得': 'przekonanie, przyjęcie (argumentu)',
  '満足': 'zadowolenie',
  '不満': 'niezadowolenie',
  '不安': 'niepokój, obawa',
  '疑問': 'pytanie, wątpliwość',
  '別れる': 'rozstawać się, żegnać',
  '出会う': 'spotkać (się), natknąć się',
  '知り合う': 'zapoznać się ze sobą',
  '親しい': 'bliski, zażyły',
  '優しい': 'łagodny, serdeczny',
  '礼': 'ukłon, podziękowanie',
  '挨拶': 'powitanie, gest grzecznościowy',
  '丁寧': 'grzeczny, uprzejmy, staranny',
  '謙虚': 'skromny, pokorny',
  '誠実': 'uczciwy, rzetelny',
  '正直': 'uczciwy, prawdomówny; szczerze',
  '率直': 'szczery, prostolinijny',
  '無理': 'niemożliwość, forsowanie; nie w porządku',
  '無駄': 'marnotrawstwo, strata, daremny',
  '勿体無い': 'szkoda marnować; nie zawdzięczać sobie',
  '自慢': 'przechwalanie się, duma',
  '自惚れ': 'buta, zarozumiałość',
  '怠ける': 'próżnować, być leniwym',
  '行動': 'działanie, czyn, postępowanie',
  '行為': 'czyn, zachowanie',
  '態度': 'postawa, zachowanie',
  'やり方': 'sposób robienia',
  '生き方': 'sposób życia',
  '考え方': 'sposób myślenia, pogląd',
  '見方': 'punkt widzenia, sposób patrzenia',
  '捉える': 'uchwycić, pojmować',
  '捉われる': 'być pochłoniętym, uwikłanym',
  '捉え方': 'sposób ujmowania, interpretacja',
  '見直す': 'zrewidować, przemyśleć ponownie',
  '見込む': 'szacować, zakładać',
  '見込み': 'prognoza, perspektywa',
  '見通し': 'perspektywa, prognoza; przejrzystość',
  '見守る': 'przyglądać się, mieć na oku',
  '見舞う': 'odwiedzać (chorego)',
  '見舞い': 'odwiedziny chorego',
  '尋ねる': 'szukać, pytać',
  '訊く': 'pytać (o zgodę), dowiadywać się',
  '伺う': 'odwiedzać (pokornie); pytać (pokornie)',
  '参る': 'przychodzić (pokornie); być pokonanym',
  '申す': 'nazywać się (pokornie); mówić (pokornie)',
  '申し込む': 'składać (wniosek), zgłaszać się',
  '申し出': 'propozycja, oferta',
  '願う': 'prosić, modlić się',
  '御願い': 'prośba (grzecz.)',
  '頼む': 'prosić, polegać',
  '頼る': 'polegać, zdawać się',
};

const CLEAN_TAGS = new Set([
  'n', 'hon', 'abbr', 'col', 'hum', 'uk', 'exp', 'arch',
  'v5u', 'v5r', 'v5s', 'female', 'vt', 'pol',
]);

function cleanMeanings(meanings) {
  return (meanings || [])
    .map((s) => (
      String(s)
        .replace(/\(([^)]*)\)/g, (all, inside) => (CLEAN_TAGS.has(inside.trim()) ? '' : all))
        .replace(/;\s*\)/g, ')')
        .replace(/\s{2,}/g, ' ')
        .replace(/\s*;\s*$/, '')
        .trim()
    ))
    .filter(Boolean);
}

function main() {
  const vocab = JSON.parse(fs.readFileSync(READ.vocab, 'utf8'));
  const kanji = JSON.parse(fs.readFileSync(READ.kanji, 'utf8'));
  const krad = readKrad();

  const kanjiMap = {};
  for (const k of kanji) {
    kanjiMap[k.character] = {
      o: k.onyomi || [],
      k: k.kunyomi || [],
      m: (k.meanings || []).slice(0, 4),
      s: k.strokes,
      l: k.level,
      rad: krad[k.character] || [],
    };
  }

  const words = vocab.map((w) => {
    const read = (w.reading && w.reading.trim()) || w.word;
    const pos = classify(w.word, w.meanings);
    const theme = themeForMeanings(w.meanings);
    const ex = (w.examples || []).slice(0, 2).map((e) => [e.ja, e.en]);
    return { w: w.word, r: read, m: cleanMeanings(w.meanings).join('; '), p: pos, t: theme, x: ex };
  });

  const data = {
    meta: {
      source: 'OpenJLPT (tanos.co.uk lists, Tatoeba examples, KANJIDIC2, kradfile2 radicals)',
      vocab: words.length,
      kanji: Object.keys(kanjiMap).length,
      rad: Object.values(kanjiMap).filter((k) => k.rad.length).length,
    },
    words,
    kanji: kanjiMap,
  };

  const js = 'window.N2GAME_DATA = ' + JSON.stringify(data) + ';';
  fs.writeFileSync(path.join(__dirname, 'n2data.js'), js);
  console.log('words:', words.length, '| kanji:', Object.keys(kanjiMap).length);
  const dist = {};
  for (const w of words) { const k = w.p; dist[k] = (dist[k] || 0) + 1; }
  console.log('POS dist:', JSON.stringify(dist));
}

main();